export const PKG_PREFIX = '@multiple-package-project'
export const PKG_NAME = 'multiple-package-project'
export const PKG_BRAND_NAME = 'multiple-package-project'
export const PKG_CAMELCASE_LOCAL_NAME = 'multiple-package-project'
export const PKG_CAMELCASE_NAME = 'multiple-package-project'